### ISSUE TITLE
eslint-plugin-deprecation

### ISSUE THREAD

**Issue by jill64** [jill64/jill64#19]
```yml
parserOptions:
  ecmaVersion: 2020
  sourceType: module
  project: ./tsconfig.json
plugins:
  - '@typescript-eslint'
  - deprecation
rules:
  deprecation/deprecation: error
```

```

    "eslint-plugin-deprecation": "2.0.0",
```

```
chore: add eslint deprecation rule
```
